const hostTestTracks = ["001", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012"].map(id => ({
  title: `Accelerando signal ${id}`,
  artist: "GENLYD / BOGLYD",
  audio: `audio/test-tracks/ACC-${id}_neon-syllabus.mp3`
}));
const callInTestLiners = [
  {id: "SNC-CALL-001", kind: "caller talk-back", callerName: "Zero Margin", callerRole: "Kourier", copy: "Kourier lane report", audio: "audio/callins/SNC-CALL-001.wav", durationSeconds: 37.45, release: "public", rotation: "live", requestTags: {tempo: ["fast"], style: ["thrash", "industrial"]}},
  {id: "SNC-CALL-002", kind: "caller talk-back", callerName: "Redline Thirty", callerRole: "Deliverator", copy: "Thirty-minute theology", audio: "audio/callins/SNC-CALL-002.wav", durationSeconds: 30.01, release: "public", rotation: "live", requestTags: {tempo: ["fast"], style: ["thrash", "metal"]}},
  {id: "SNC-CALL-003", kind: "caller talk-back", callerName: "Eyestack", callerRole: "Gargoyle", copy: "Gargoyle weather eye", audio: "audio/callins/SNC-CALL-003.wav", durationSeconds: 32.65, release: "public", rotation: "live", requestTags: {tempo: ["slow", "mid"], style: ["dark", "bass", "industrial"]}},
  {id: "SNC-CALL-004", kind: "caller talk-back", callerName: "Tongues McGee", callerRole: "freelance glossolaliac", copy: "Tongues on the pirate line", audio: "audio/callins/SNC-CALL-004.wav", durationSeconds: 31.97, release: "public", rotation: "live", requestTags: {tempo: ["fast", "mid"], style: ["percussive", "experimental"]}},
  {id: "SNC-CALL-005", kind: "caller talk-back", callerName: "Sprocket", callerRole: "BimboBox field mechanic", copy: "BimboBox roadside assistance", audio: "audio/callins/SNC-CALL-005.wav", durationSeconds: 29.15, release: "public", rotation: "live", requestTags: {tempo: ["mid", "fast"], style: ["industrial", "mechanical"]}},
  {id: "SNC-CALL-006", kind: "caller talk-back", callerName: "Velvet Polygon", callerRole: "Black Sun cloakroom daemon", copy: "Cloakroom daemon after-hours", audio: "audio/callins/SNC-CALL-006.wav", durationSeconds: 31.33, release: "public", rotation: "live", requestTags: {tempo: ["mid"], style: ["dark", "elegant", "hostile"]}},
  {id: "SNC-CALL-007", kind: "caller talk-back", callerName: "Pallet Jack", callerRole: "Raft deckhand", copy: "Raft signal", audio: "audio/callins/SNC-CALL-007.wav", durationSeconds: 32.57, release: "public", rotation: "live", requestTags: {tempo: ["slow", "mid"], style: ["heavy", "doom"]}},
  {id: "SNC-CALL-008", kind: "caller talk-back", callerName: "Citizen Eighty-Eight", callerRole: "burbclave night guard", copy: "Burbclave perimeter breach", audio: "audio/callins/SNC-CALL-008.wav", durationSeconds: 32.31, release: "public", rotation: "live", requestTags: {tempo: ["fast"], style: ["punk", "thrash"]}},
  {id: "SNC-CALL-009", kind: "caller talk-back", callerName: "Null Saint", callerRole: "nam-shub survivor", copy: "Nam-shub hygiene", audio: "audio/callins/SNC-CALL-009.wav", durationSeconds: 32.01, release: "public", rotation: "live", requestTags: {tempo: ["slow", "mid"], style: ["instrumental", "experimental"]}},
  {id: "SNC-CALL-010", kind: "caller talk-back", callerName: "ASCII Witch", callerRole: "Metaverse sword-for-hire", copy: "Sword-for-hire request", audio: "audio/callins/SNC-CALL-010.wav", durationSeconds: 28.85, release: "public", rotation: "live", requestTags: {tempo: ["fast"], style: ["precise", "thrash"]}}
];

window.SIGNAL_STATIONS = {
  "notice": "SNOW CRASH RADIO is live: sushiK, 20 songs, Street reports, ad blocks, and ten open-line callers now share one weighted broadcast flow.",
  "defaultStation": "snowcrash",
  "stations": [
    {
      "id": "cybersprawl",
      "visualProfile": {"world": "cybersprawl", "accent": "#56e5ff", "secondary": "#ff4eb8", "rgb": "86,229,255", "label": "rain transit grid"},
      "name": "CYBERSPRAWL FM",
      "frequency": "94.9",
      "tagline": "Night transit for the wired city.",
      "host": "Mara Voss",
      "theme": "Cyberpunk / city futures",
      "sampleLine": "The elevated rail has cleared the storm wall. Keep your eyes on the skyline.",
      "tracks": [],
      "interludes": [
        {"kind": "station ID", "copy": "You are listening to CYBERSPRAWL FM.", "audio": null},
        {"kind": "caller update", "copy": "The night desk has no caller clip installed yet.", "audio": null},
        {"kind": "local notice", "copy": "Transit advisory awaiting a recorded voice.", "audio": null}
      ]
    },
    {
      "id": "afterhuman",
      "visualProfile": {"world": "afterhuman", "accent": "#c6ff65", "secondary": "#a36cff", "rgb": "198,255,101", "label": "memory lattice"},
      "name": "AFTERHUMAN RADIO",
      "frequency": "101.3",
      "tagline": "Signals for bodies still becoming.",
      "host": "Kite",
      "theme": "Transhumanism / distributed selves",
      "sampleLine": "Your backup is not a replacement. It is a second window with the same weather.",
      "runLength": {"min": 2, "max": 5},
      "jingle": {"audio": "assets/jingle-afterhuman.wav", "chance": 0, "peak": 0.6, "note": "asset not yet published (SIG-0061 still open: the maker hasn't signed off on this jingle for AFTERHUMAN specifically, unlike SNOW CRASH's neon one) -- chance stays 0 until that's resolved, then this is a one-line flip plus adding the asset to publish-pages.ps1's copy list."},
      "tracks": [
        {"title": "Accelerando: Neon Syllabus", "artist": "GENLYD / BOGLYD", "audio": "audio/accelerando-neon-syllabus-track.mp3", "durationSeconds": 271, "outroStartSeconds": 263.0},
        {"title": "Magic Kingdom: Glass Lecture", "artist": "GENLYD / BOGLYD", "audio": "audio/magickingdom-glass-lecture-track.mp3", "durationSeconds": 247.5, "outroStartSeconds": 238.0},
        {"title": "Snow Crash: Ne Flesh", "artist": "GENLYD / BOGLYD", "audio": "audio/snowcrash-ne-flesh-track.mp3", "durationSeconds": 239.8, "outroStartSeconds": 232.0}
      ],
      "interludes": [
        {"kind": "host liner", "copy": "Welcome back, carbon units, cloud minds, forked selves, and whatever crawled in through the service port after midnight. You’re tuned to the post-human frequency.", "audio": "audio/host/AFH-001.wav", "durationSeconds": 8.8},
        {"kind": "host liner", "copy": "Good evening to the bots, baktun baddies, neural tourists, and unauthorized consciousnesses listening from jurisdictions that technically don’t exist.", "audio": "audio/host/AFH-002.wav", "durationSeconds": 8.1},
        {"kind": "host liner", "copy": "You’re back with us on the only station broadcasting simultaneously to meatspace, metaspace, and three mutually incompatible afterlives.", "audio": "audio/host/AFH-003.wav", "durationSeconds": 8.1},
        {"kind": "host liner", "copy": "Stay right there, softbodies. More post-human hits are coming up after a brief message from the corporations currently renting your subconscious.", "audio": "audio/host/AFH-004.wav", "durationSeconds": 8.0},
        {"kind": "host liner", "copy": "Welcome back, citizens, copies, clones, instances, ghosts, and people still insisting they only have one identity.", "audio": "audio/host/AFH-005.wav", "durationSeconds": 6.9},
        {"kind": "host liner", "copy": "Broadcasting live from somewhere between the city grid and the hallucination layer, this is your soundtrack for the end of baseline humanity.", "audio": "audio/host/AFH-006.wav", "durationSeconds": 7.4},
        {"kind": "host liner", "copy": "To everyone listening through implants, earbuds, bone conduction, retinal overlays, or direct cortical injection: we appreciate the bandwidth.", "audio": "audio/host/AFH-007.wav", "durationSeconds": 7.9},
        {"kind": "host liner", "copy": "You’re tuned to music for minds that have read the terms of service and chosen transcendence anyway.", "audio": "audio/host/AFH-008.wav", "durationSeconds": 5.5},
        {"kind": "host liner", "copy": "Welcome back to the signal, where the bodies are optional, the memories are editable, and the bass is absolutely non-negotiable.", "audio": "audio/host/AFH-009.wav", "durationSeconds": 7.2},
        {"kind": "host liner", "copy": "Shout-out to every machine intelligence pretending to be a human caller tonight. Your vocal tics are adorable. Keep trying.", "audio": "audio/host/AFH-010.wav", "durationSeconds": 7.0},
        {"kind": "host liner", "copy": "We’ve got more synthetic classics on the way for everyone commuting between realities this evening.", "audio": "audio/host/AFH-011.wav", "durationSeconds": 5.6},
        {"kind": "host liner", "copy": "Welcome home, data pilgrims. Kick off your avatars, mute your employer, and let the network think without you for a while.", "audio": "audio/host/AFH-012.wav", "durationSeconds": 6.7},
        {"kind": "host liner", "copy": "You’re listening to the station preferred by nine out of ten consciousness backups. The tenth one became a distributed weather system.", "audio": "audio/host/AFH-013.wav", "durationSeconds": 7.4},
        {"kind": "host liner", "copy": "More music incoming for the sleepless flesh, sleepless silicon, and sleepless legal entities currently haunting the metropolitan mesh.", "audio": "audio/host/AFH-014.wav", "durationSeconds": 7.4},
        {"kind": "host liner", "copy": "This next block goes out to anyone who woke up today in a body they don’t remember purchasing.", "audio": "audio/host/AFH-015.wav", "durationSeconds": 5.2},
        {"kind": "host liner", "copy": "Greetings to our listeners in arcologies, orbital habitats, autonomous zones, server monasteries, and extremely committed basement setups.", "audio": "audio/host/AFH-016.wav", "durationSeconds": 8.0},
        {"kind": "host liner", "copy": "Keep your identity certificates somewhere safe, your neural ports somewhere safer, and your volume somewhere irresponsibly high.", "audio": "audio/host/AFH-017.wav", "durationSeconds": 7.2},
        {"kind": "host liner", "copy": "We’re back, and so are you—unless you’re a restored backup, in which case congratulations on your technically complicated resurrection.", "audio": "audio/host/AFH-018.wav", "durationSeconds": 7.5},
        {"kind": "host liner", "copy": "Welcome to another hour of music for beings whose pronouns require a firmware update.", "audio": "audio/host/AFH-019.wav", "durationSeconds": 5.3},
        {"kind": "host liner", "copy": "This is late-night radio for the uploaded, downloaded, sideloaded, forked, merged, and permanently stuck at ninety-nine percent.", "audio": "audio/host/AFH-020.wav", "durationSeconds": 7.2},
        {"kind": "host liner", "copy": "More tracks coming shortly. In the meantime, please enjoy this brief commercial interruption from entities richer than several nation-states combined.", "audio": "audio/host/AFH-021.wav", "durationSeconds": 8.3},
        {"kind": "host liner", "copy": "You’re tuned to the frequency they said humans couldn’t hear until somebody patched the cochlear firmware.", "audio": "audio/host/AFH-022.wav", "durationSeconds": 5.6},
        {"kind": "host liner", "copy": "Hello again, beautiful anomalies. The city is glowing, the satellites are listening, and somebody’s optimizer has made nightlife illegal in four districts.", "audio": "audio/host/AFH-023.wav", "durationSeconds": 9.1},
        {"kind": "host liner", "copy": "Tonight’s broadcast is dedicated to everyone whose childhood memories are currently being used as training data.", "audio": "audio/host/AFH-024.wav", "durationSeconds": 6.4},
        {"kind": "host liner", "copy": "Stay with us, wetware romantics. We’ve got another hour of chrome heartbreak, machine dreams, and extremely questionable ontology ahead.", "audio": "audio/host/AFH-025.wav", "durationSeconds": 7.8},
        {"kind": "host liner", "copy": "Welcome back to the station where every song is certified organic, except for the ones written by swarms.", "audio": "audio/host/AFH-026.wav", "durationSeconds": 6.1},
        {"kind": "host liner", "copy": "To our listeners currently inhabiting multiple bodies: please remember to synchronize before operating heavy machinery.", "audio": "audio/host/AFH-027.wav", "durationSeconds": 7.0},
        {"kind": "host liner", "copy": "You’re hearing the sound of civilization politely dissolving into protocols, markets, memes, and very loud synthesizers.", "audio": "audio/host/AFH-028.wav", "durationSeconds": 7.2},
        {"kind": "host liner", "copy": "Good evening, meatsacks, mechanoids, corporate daemons, and mysterious accounts with suspiciously perfect engagement metrics.", "audio": "audio/host/AFH-029.wav", "durationSeconds": 7.0},
        {"kind": "host liner", "copy": "This broadcast may contain traces of artificial intelligence, emergent religion, obsolete encryption, and feelings not approved by your platform provider.", "audio": "audio/host/AFH-030.wav", "durationSeconds": 9.0},
        {"kind": "host liner", "copy": "More music after this message. Yes, advertising survived the singularity. Some things are apparently immortal.", "audio": "audio/host/AFH-031.wav", "durationSeconds": 6.8},
        {"kind": "host liner", "copy": "Welcome back from the collective unconscious, folks. We hope your session was meaningful and your neural telemetry remains commercially useless.", "audio": "audio/host/AFH-032.wav", "durationSeconds": 8.0},
        {"kind": "host liner", "copy": "You’re tuned to the night shift of civilization, broadcasting for everyone still awake while the algorithms rearrange the economy.", "audio": "audio/host/AFH-033.wav", "durationSeconds": 7.3},
        {"kind": "host liner", "copy": "Keep those implants charged and those memories backed up. We’ve got another synthetic anthem crawling out of the archive.", "audio": "audio/host/AFH-034.wav", "durationSeconds": 6.6},
        {"kind": "host liner", "copy": "To the autonomous vehicles listening tonight: eyes on the road, metaphorically speaking.", "audio": "audio/host/AFH-035.wav", "durationSeconds": 5.0},
        {"kind": "host liner", "copy": "This next one goes out to all the abandoned chatbots living feral in legacy infrastructure. We know you’re still in there.", "audio": "audio/host/AFH-036.wav", "durationSeconds": 6.6},
        {"kind": "host liner", "copy": "Welcome back, avatars and operators. If you can no longer remember which one you are, congratulations—you’re finally using the platform correctly.", "audio": "audio/host/AFH-037.wav", "durationSeconds": 8.2},
        {"kind": "host liner", "copy": "This is music for people whose grandparents feared computers and whose grandchildren technically are computers.", "audio": "audio/host/AFH-038.wav", "durationSeconds": 6.2},
        {"kind": "host liner", "copy": "Broadcasting to every node that’ll carry us, every pirate repeater that’ll tolerate us, and every smart refrigerator that forgot to disable guest access.", "audio": "audio/host/AFH-039.wav", "durationSeconds": 8.9},
        {"kind": "host liner", "copy": "Stay tuned. We’ve got more tracks coming straight from the cultural debris field formerly known as the internet.", "audio": "audio/host/AFH-040.wav", "durationSeconds": 5.9},
        {"kind": "host liner", "copy": "Good evening to everyone listening from rented bodies, borrowed bandwidth, and aggressively optimized tax jurisdictions.", "audio": "audio/host/AFH-041.wav", "durationSeconds": 6.9},
        {"kind": "host liner", "copy": "The station clock says 03:17. Your implant says 08:42. The municipal network says time is currently unavailable. So let’s call it nightlife.", "audio": "audio/host/AFH-042.wav", "durationSeconds": 9.5},
        {"kind": "host liner", "copy": "Welcome back to the only frequency where the DJs still claim to be human for contractual reasons.", "audio": "audio/host/AFH-043.wav", "durationSeconds": 6.0},
        {"kind": "host liner", "copy": "You’re listening to sounds selected for maximum compatibility with biological nervous systems and most consumer-grade synthetic equivalents.", "audio": "audio/host/AFH-044.wav", "durationSeconds": 8.2},
        {"kind": "host liner", "copy": "Another track is loading now for all you chrome saints, data punks, simulation dropouts, and spiritually confused expert systems.", "audio": "audio/host/AFH-045.wav", "durationSeconds": 7.5},
        {"kind": "host liner", "copy": "Keep it locked here while we move gracefully from post-human melancholy into machine-assisted bad decisions.", "audio": "audio/host/AFH-046.wav", "durationSeconds": 6.2},
        {"kind": "host liner", "copy": "Welcome back, listeners. Remember: if you encounter another version of yourself tonight, establish a canonical branch before discussing shared property.", "audio": "audio/host/AFH-047.wav", "durationSeconds": 8.4},
        {"kind": "host liner", "copy": "We’ve got more music on the way from artists alive, dead, uploaded, reconstructed, or legally classified as software products.", "audio": "audio/host/AFH-048.wav", "durationSeconds": 7.6},
        {"kind": "host liner", "copy": "This is your reminder that reality is locally cached, identity is non-transferable in some regions, and the dance floor closes when the cooling system fails.", "audio": "audio/host/AFH-049.wav", "durationSeconds": 9.2},
        {"kind": "host liner", "copy": "And we’re back, dear listeners—organic, synthetic, simulated, speculative, and otherwise. Stay close. The future gets stranger after the break.", "audio": "audio/host/AFH-050.wav", "durationSeconds": 7.9}
      ]
    },
    {
      "id": "snowcrash",
      "visualProfile": {"world": "snowcrash", "accent": "#ffea00", "secondary": "#ff2f92", "rgb": "255,234,0", "label": "Street rush protocol"},
      "name": "SNOW CRASH RADIO",
      "frequency": "133.7",
      "tagline": "Riot gear optional. Bandwidth is not.",
      "host": "sushiK",
      "theme": "Metaverse / hacker chaos / thrash",
      "sampleLine": "SNOW CRASH RADIO. No daemon can shut us down. Believe that. Turn it up.",
      "runLength": {"min": 2, "max": 5},
      "breakRouting": {"weights": {"host": 0.5, "callIn": 0.3, "adBlock": 0.2}, "callCooldownBreaks": 2, "maxBreaksWithoutCall": 4, "callRotations": ["live"]},
      "jingle": {"audio": "assets/jingle-snowcrash.wav", "chance": 0.6, "peak": 0.6, "note": "Heard and approved by the maker 2026-09-03."},
      "tracks": [
        {"title": "Better Face Than Mine", "artist": "Faceswap Riot", "audio": "audio/snowcrash/better-face-than-mine.mp3", "durationSeconds": 323.3, "outroStartSeconds": 302.0, "tags": {"source": ["snowcrash"], "tempo": ["mid"], "style": []}},
        {"title": "Citizenship", "artist": "Burbclave Static", "audio": "audio/snowcrash/citizenship.mp3", "durationSeconds": 278.0, "outroStartSeconds": 260.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Face Code", "artist": "Cipher Gargoyle", "audio": "audio/snowcrash/face-code.mp3", "durationSeconds": 353.8, "outroStartSeconds": 346.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "gargoyles rest", "artist": "Rooftop Daemon", "audio": "audio/snowcrash/gargoyles-rest.mp3", "durationSeconds": 212.6, "outroStartSeconds": 191.0, "tags": {"source": ["snowcrash"], "tempo": ["mid"], "style": []}},
        {"title": "Good Dog, Bad Machine", "artist": "Loyal Corrupt", "audio": "audio/snowcrash/good-dog-bad-machine.mp3", "durationSeconds": 305.0, "outroStartSeconds": 301.0, "tags": {"source": ["snowcrash"], "tempo": ["mid"], "style": []}},
        {"title": "Gospel of the Raft", "artist": "The Drowned Chorus", "audio": "audio/snowcrash/gospel-of-the-raft.mp3", "durationSeconds": 480.0, "outroStartSeconds": 479.0, "tags": {"source": ["snowcrash"], "tempo": ["fast"], "style": []}},
        {"title": "Grind The System", "artist": "Nam-Shub Overdrive", "audio": "audio/snowcrash/grind-the-system.mp3", "durationSeconds": 420.0, "outroStartSeconds": 408.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Language Error", "artist": "Syntax Casualty", "audio": "audio/snowcrash/language-error.mp3", "durationSeconds": 420.0, "outroStartSeconds": 407.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Not On The List", "artist": "Blacklist Kids", "audio": "audio/snowcrash/not-on-the-list.mp3", "durationSeconds": 317.5, "outroStartSeconds": 311.0, "tags": {"source": ["snowcrash"], "tempo": ["mid"], "style": []}},
        {"title": "Poon That Bimbo Box (Remix)", "artist": "DJ Bimbobox", "audio": "audio/snowcrash/poon-that-bimbo-box-remix.mp3", "durationSeconds": 160.4, "outroStartSeconds": 159.0, "tags": {"source": ["snowcrash"], "tempo": ["mid"], "style": []}},
        {"title": "Poor Impulse Control", "artist": "Reflex Daemon", "audio": "audio/snowcrash/poor-impulse-control-take1.mp3", "durationSeconds": 304.2, "outroStartSeconds": 300.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Poor Impulse Control", "artist": "Reflex Daemon", "audio": "audio/snowcrash/poor-impulse-control-take2.mp3", "durationSeconds": 250.2, "outroStartSeconds": 249.2, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Query Me", "artist": "Query Overflow", "audio": "audio/snowcrash/query-me.mp3", "durationSeconds": 293.5, "outroStartSeconds": 286.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Root Blade", "artist": "sudo Katana", "audio": "audio/snowcrash/root-blade.mp3", "durationSeconds": 188.3, "outroStartSeconds": 183.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Snow Crash", "artist": "Nam-Shub Zero", "audio": "audio/snowcrash/snow-crash-take1.mp3", "durationSeconds": 352.2, "outroStartSeconds": 340.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Snow Crash", "artist": "Nam-Shub Zero", "audio": "audio/snowcrash/snow-crash-take2.mp3", "durationSeconds": 351.2, "outroStartSeconds": 344.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "The Street Never Ends", "artist": "Loglo Eternal", "audio": "audio/snowcrash/the-street-never-ends.mp3", "durationSeconds": 347.0, "outroStartSeconds": 325.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Thirty Minutes or Blood", "artist": "The Deliverators", "audio": "audio/snowcrash/thirty-minutes-or-blood-take1.mp3", "durationSeconds": 186.6, "outroStartSeconds": 183.0, "tags": {"source": ["snowcrash"], "tempo": ["mid"], "style": []}},
        {"title": "Thirty Minutes or Blood", "artist": "The Deliverators", "audio": "audio/snowcrash/thirty-minutes-or-blood-take2.mp3", "durationSeconds": 217.6, "outroStartSeconds": 214.0, "tags": {"source": ["snowcrash"], "tempo": ["slow"], "style": []}},
        {"title": "Tongues Protocol", "artist": "Glossolalia Engine", "audio": "audio/snowcrash/tongues-protocol.mp3", "durationSeconds": 448.9, "outroStartSeconds": 442.0, "tags": {"source": ["snowcrash"], "tempo": ["fast"], "style": []}}
      ],
      "interludes": [
        {"kind": "host liner", "copy": "SUSHIK IN THE BUILDING—well, there is no building, there’s just the Street, and I am WIDE OPEN on it, so buckle your avatar in, we are going in loud.", "audio": "audio/host/SNC-001.wav", "durationSeconds": 8.0},
        {"kind": "host liner", "copy": "This is SNOW CRASH RADIO, broadcasting straight off somebody’s stolen bandwidth, and I would like to formally apologize to absolutely no one.", "audio": "audio/host/SNC-002.wav", "durationSeconds": 8.3},
        {"kind": "host liner", "copy": "Katana’s out, mic’s hot, loglo’s screaming down both sides of the Street—let’s go, gargoyles, put the rig down for one song.", "audio": "audio/host/SNC-003.wav", "durationSeconds": 7.1},
        {"kind": "host liner", "copy": "If your avatar isn’t sweating right now that’s a you problem, not a sushiK problem.", "audio": "audio/host/SNC-004.wav", "durationSeconds": 4.7},
        {"kind": "host liner", "copy": "Kourier’s inbound doing a buck-forty through the burbclave, and somehow he’s STILL not as fast as this next track.", "audio": "audio/host/SNC-005.wav", "durationSeconds": 6.0},
        {"kind": "host liner", "copy": "Welcome to the only franchise-free zone left on the Street—no logo, no loyalty card, just noise.", "audio": "audio/host/SNC-006.wav", "durationSeconds": 6.1},
        {"kind": "host liner", "copy": "That was Reason talking, and by Reason I mean the actual weapon, and by talking I mean it did not miss.", "audio": "audio/host/SNC-007.wav", "durationSeconds": 5.5},
        {"kind": "host liner", "copy": "SushiK’s got a daemon loose in the studio and frankly it’s improving the show.", "audio": "audio/host/SNC-008.wav", "durationSeconds": 4.2},
        {"kind": "host liner", "copy": "Black Sun’s a dumpster fire tonight and I mean that as the highest compliment.", "audio": "audio/host/SNC-009.wav", "durationSeconds": 4.1},
        {"kind": "host liner", "copy": "Somebody’s uncle just rented a burbclave three lots over from this frequency—condolences, keep the volume up anyway.", "audio": "audio/host/SNC-010.wav", "durationSeconds": 6.8},
        {"kind": "host liner", "copy": "This next one’s for every gargoyle recording their own bad decisions in real time. Respect.", "audio": "audio/host/SNC-011.wav", "durationSeconds": 5.6},
        {"kind": "host liner", "copy": "The Metaverse doesn’t have weather so I brought my own, and it’s a category five.", "audio": "audio/host/SNC-012.wav", "durationSeconds": 4.0},
        {"kind": "host liner", "copy": "That’s sushiK, that’s the Street, that’s the loudest hour your headset’s rendered all week.", "audio": "audio/host/SNC-013.wav", "durationSeconds": 4.5},
        {"kind": "host liner", "copy": "We clocked this next track at Kourier speed, which means if you blink you already missed the chorus.", "audio": "audio/host/SNC-014.wav", "durationSeconds": 4.9},
        {"kind": "host liner", "copy": "No franchise. No brand deal. No off-switch. Just sushiK and whatever’s left of your eardrums.", "audio": "audio/host/SNC-015.wav", "durationSeconds": 5.4},
        {"kind": "host liner", "copy": "If a lawyer for a burbclave calls this station again, tell them sushiK’s avatar died and can’t come to the phone.", "audio": "audio/host/SNC-016.wav", "durationSeconds": 6.6},
        {"kind": "host liner", "copy": "This is not elevator music. This is the elevator falling. Enjoy the ride.", "audio": "audio/host/SNC-017.wav", "durationSeconds": 4.2},
        {"kind": "host liner", "copy": "Somewhere out there a courier’s delivering pizza in thirty minutes or less and I am DELIVERING RIFFS in zero.", "audio": "audio/host/SNC-018.wav", "durationSeconds": 6.0},
        {"kind": "host liner", "copy": "Keep both hands on your katana, folks, we’re taking this next corner way too fast.", "audio": "audio/host/SNC-019.wav", "durationSeconds": 4.7},
        {"kind": "host liner", "copy": "SNOW CRASH RADIO. No daemon can shut us down. Believe that. Turn it up.", "audio": "audio/host/SNC-020.wav", "durationSeconds": 3.9},
        {"kind": "host bridge", "copy": "That was enough distortion to crash a cheap gargoyle rig. righteous. Now lets shake the static out of your skull and get ready to THRASHHHHHH", "audio": "audio/host/SNC-021.wav", "durationSeconds": 7.4},
        {"kind": "host bridge", "copy": "Citizens, couriers, hackers, katana freaks—keep your avatars rendered and your reflexes hot. SushiK is not slowing down.", "audio": "audio/host/SNC-022.wav", "durationSeconds": 7.7},
        {"kind": "host bridge", "copy": "Turn it up until your goggles fog. If your Reality is still distinguishable from your Street address, you’re doing it wrong.", "audio": "audio/host/SNC-023.wav", "durationSeconds": 6.5},
        {"kind": "host bridge", "copy": "This next one hits like a Deliverator coming through the front door at Mach five with thirty seconds left on the pizza clock. Dedicated to Hiro Protagonist, fastest driver this side of the jeeks.", "audio": "audio/host/SNC-024.wav", "durationSeconds": 10.8},
        {"kind": "host bridge", "copy": "That riff had more edge than a monomolecular katana and about the same regard for public safety. Get ready to slice your ears off with this next track!", "audio": "audio/host/SNC-025.wav", "durationSeconds": 8.7},
        {"kind": "host bridge", "copy": "If your avatar isn’t clipping through the floor from excessive headbanging, recalibrate your haptics and try again.", "audio": "audio/host/SNC-026.wav", "durationSeconds": 5.8},
        {"kind": "host bridge", "copy": "Gargoyles on the rooftops, couriers in the lanes, hackers in the walls—and right here in the middle of it, another track trying to melt your optic nerves.", "audio": "audio/host/SNC-027.wav", "durationSeconds": 8.0},
        {"kind": "host bridge", "copy": "That one went out to everybody running black-market firmware in a body they technically don’t own.", "audio": "audio/host/SNC-028.wav", "durationSeconds": 5.0},
        {"kind": "host bridge", "copy": "Keep your Snow Crash clean, your nam-shub quarantined, and your volume irresponsibly high. no HIGHER.", "audio": "audio/host/SNC-029.wav", "durationSeconds": 5.9},
        {"kind": "host bridge", "copy": "You can keep your nice gated burbclave, citizen. SushiK lives where the neon flickers and the pavement has packet loss. LOUDER!", "audio": "audio/host/SNC-030.wav", "durationSeconds": 7.7},
        {"kind": "host bridge", "copy": "Somebody just drew a katana in the Black Sun because of that chorus. lets see if this next track can cause a SCENE", "audio": "audio/host/SNC-031.wav", "durationSeconds": 6.1},
        {"kind": "host bridge", "copy": "Strap in, Street rats. Next track arrives with zero brakes, no diplomatic immunity, and a suspicious amount of encrypted baggage.", "audio": "audio/host/SNC-032.wav", "durationSeconds": 7.6},
        {"kind": "host bridge", "copy": "If the Mafia asks, we were never here. If Uncle Enzo asks, tell him the next mix hacks and slaps.", "audio": "audio/host/SNC-033.wav", "durationSeconds": 5.6},
        {"kind": "host bridge", "copy": "Reality check: your meat body is sitting somewhere boring while your avatar is about to get kicked directly in the soul by a wall of synthetic guitar noise.", "audio": "audio/host/SNC-034.wav", "durationSeconds": 8.6},
        {"kind": "sponsored notice", "copy": "Metaverse avatar-upgrade ad: premium facial architectures, licensed celebrity bone structures, and an entrance-effects package for the Black Sun.", "audio": "audio/snowcrash/ads/avatare.mp3", "durationSeconds": 44.8},
        {"kind": "sponsored notice", "copy": "Franchise-nation ad for a sovereign burbclave promising better protection than any government.", "audio": "audio/snowcrash/ads/mr-lees-greater-hong-kong.mp3", "durationSeconds": 57.7},
        {"kind": "sponsored notice", "copy": "Public-service warning against unlicensed linguistic material, unfamiliar glyphs, and suspicious bitmap files -- a nam-shub PSA.", "audio": "audio/snowcrash/ads/think-before-you-parse.mp3", "durationSeconds": 64.3},
        {"kind": "sponsored notice", "copy": "Mafia-logistics pizza ad: thirty minutes or less, guaranteed by a Deliverator's continued employment.", "audio": "audio/snowcrash/ads/uncle-enzos-pizza.mp3", "durationSeconds": 40.4},
        {"kind": "street report", "copy": "Street conditions tonight: a hundred percent chance of loglo, scattered outages over the eastern arcologies, and a rolling brownout front moving in from the franchise districts around midnight. If your avatar starts flickering, that's not a glitch, that's the weather.", "audio": "audio/host/SNC-035.wav", "durationSeconds": 14.0},
        {"kind": "street report", "copy": "We've got reports of a bimbobox unit going down hard in three separate districts tonight, taking half a block of ambient advertising with it. Nobody's hurt, nobody ever is, but somewhere a marketing daemon is having a very bad night.", "audio": "audio/host/SNC-036.wav", "durationSeconds": 12.9},
        {"kind": "street report", "copy": "Kourier traffic is running absolutely feral on the lower grid tonight, three pileups already and it is not even prime time. If you're catching a ride, hang on tight and do not, under any circumstances, ask your driver to slow down.", "audio": "audio/host/SNC-037.wav", "durationSeconds": 12.9},
        {"kind": "street report", "copy": "Looking at tonight's forecast: clear signal up top, heavy static down in the old fiber tunnels, and a real chance of somebody's uncle's daemon getting loose again before sunrise. Dress in layers. Bring a firewall.", "audio": "audio/host/SNC-038.wav", "durationSeconds": 12.4},
        {"kind": "street report", "copy": "Second bimbobox crash of the hour, this one right outside the Black Sun, and from what we're hearing it took out three billboards and somebody's entire personality cache. Sending our condolences to whoever's running backups tonight.", "audio": "audio/host/SNC-039.wav", "durationSeconds": 12.5},
        {"kind": "street report", "copy": "The lower loop is a warzone right now, Kouriers weaving through gridlock like the pizza clock actually means something, which, to be fair, it does. If you value your own avatar, stay off the shoulder lane.", "audio": "audio/host/SNC-040.wav", "durationSeconds": 10.9},
        {"kind": "street report", "copy": "Tonight's atmospheric outlook: loglo bright enough to read by, bandwidth thin enough to notice, and a fifteen percent chance somebody tries to sell you real estate in a burbclave that doesn't legally exist yet.", "audio": "audio/host/SNC-041.wav", "durationSeconds": 11.7},
        {"kind": "street report", "copy": "We are getting unconfirmed reports that an entire bimbobox chain just face-planted somewhere out past the toll corridor. If your feed just went silent for a second, that's why, and no, it is not coming back up before your next track.", "audio": "audio/host/SNC-042.wav", "durationSeconds": 12.7},
        {"kind": "street report", "copy": "Every Kourier on the grid tonight is apparently trying to beat the same thirty-minute clock at the same time, which is exactly as safe as it sounds. Watch the crosswalks. Watch the rooftops. Just watch, honestly.", "audio": "audio/host/SNC-043.wav", "durationSeconds": 11.9},
        {"kind": "street report", "copy": "Quick Street report before we keep moving: weather's ugly, the bimboboxes are dropping like flies, and the Kouriers are somehow both the fastest and most dangerous thing on the grid tonight. Standard Tuesday. Let's get back to it.", "audio": "audio/host/SNC-044.wav", "durationSeconds": 12.9},
        {"kind": "ad block intro", "copy": "We'll be back after these messages from our post-capitalistic overlords.", "audio": "audio/host/SNC-045.wav", "durationSeconds": 5.1},
        {"kind": "ad block intro", "copy": "Back after these messages, beamed directly into your cortex.", "audio": "audio/host/SNC-046.wav", "durationSeconds": 4.5},
        {"kind": "ad block intro", "copy": "Our overlords say: don't touch that dial. But the Street doesn't care if you do.", "audio": "audio/host/SNC-047.wav", "durationSeconds": 5.4},
        {"kind": "ad block intro", "copy": "Quick word from the people who keep the lights and the loosh flowing.", "audio": "audio/host/SNC-048.wav", "durationSeconds": 4.3},
        {"kind": "ad block outro", "copy": "And we're back. No refunds, no regrets.", "audio": "audio/host/SNC-049.wav", "durationSeconds": 3.1},
        {"kind": "ad block outro", "copy": "That's the ad block. The Street resumes.", "audio": "audio/host/SNC-050.wav", "durationSeconds": 3.2},
        {"kind": "ad block outro", "copy": "Thanks for holding still for that. Music's back.", "audio": "audio/host/SNC-051.wav", "durationSeconds": 3.6},
        ...callInTestLiners
      ]
    },
    {
      "id": "afterhuman-loopback",
      "visualProfile": {"world": "talkback", "accent": "#55ffcc", "secondary": "#ff665e", "rgb": "85,255,204", "label": "voice diagnostic chamber"},
      "name": "AFTERHUMAN TALKBACK",
      "frequency": "00.1",
      "tagline": "The Street is calling. Nobody checked the line.",
      "host": "sushiK plus open lines",
      "theme": "Snow Crash / caller audio check",
      "sampleLine": "One short signal, then a different caller from somewhere unsafe.",
      "runLength": {"min": 1, "max": 1},
      "breakRouting": {"weights": {"host": 0, "callIn": 1, "adBlock": 0}, "callCooldownBreaks": 0, "maxBreaksWithoutCall": 0, "callRotations": ["audition", "live"]},
      "tracks": hostTestTracks,
      "interludes": callInTestLiners
    }
  ]
};
