// GENERATED by build-radio-data.ps1 from _SYSTEM/data/projects-data.js - do not hand-edit.
// Counts only, no free text: safe to sync publicly (see publish-pages.ps1).
window.RADIO_DATA = { generated: "2026-08-25 11:12", stations: [
    {
        "name":  "ACIDGOBLIN",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  150,
        "recent1d":  86,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "ARCHAEOCUTIES",
        "stage":  "research",
        "priority":  "medium",
        "core":  false,
        "recent7d":  17,
        "recent1d":  4,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "BRANDING",
        "stage":  "development",
        "priority":  "high",
        "core":  true,
        "recent7d":  17,
        "recent1d":  11,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "DYST",
        "stage":  "development",
        "priority":  "high",
        "core":  false,
        "recent7d":  25,
        "recent1d":  25,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "FLUID_LAB",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  3,
        "recent1d":  1,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "GENLYD",
        "stage":  "cooking",
        "priority":  "medium",
        "core":  false,
        "recent7d":  3,
        "recent1d":  1,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "GROUND",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  5,
        "recent1d":  3,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "GROWTH_LAB",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  43,
        "recent1d":  9,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "HOME",
        "stage":  "on-hold",
        "priority":  "low",
        "core":  false,
        "recent7d":  6,
        "recent1d":  6,
        "totalHist":  72,
        "restingDays":  null
    },
    {
        "name":  "JORD",
        "stage":  "cooking",
        "priority":  "medium",
        "core":  false,
        "recent7d":  6,
        "recent1d":  3,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "KLIPP",
        "stage":  "in-work",
        "priority":  "medium",
        "core":  false,
        "recent7d":  7,
        "recent1d":  7,
        "totalHist":  85,
        "restingDays":  null
    },
    {
        "name":  "PAUSE",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  2,
        "recent1d":  2,
        "totalHist":  70,
        "restingDays":  null
    },
    {
        "name":  "PORTFOLIO",
        "stage":  "in-work",
        "priority":  "medium",
        "core":  true,
        "recent7d":  150,
        "recent1d":  150,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "RAD_COVS",
        "stage":  "in-work",
        "priority":  "medium",
        "core":  false,
        "recent7d":  57,
        "recent1d":  55,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "RENDER_LAB",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  5,
        "recent1d":  3,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "RENKON",
        "stage":  "in-work",
        "priority":  "medium",
        "core":  false,
        "recent7d":  34,
        "recent1d":  10,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "RIMEDAEMON",
        "stage":  "cooking",
        "priority":  "medium",
        "core":  false,
        "recent7d":  9,
        "recent1d":  9,
        "totalHist":  46,
        "restingDays":  null
    },
    {
        "name":  "SAMLING",
        "stage":  "on-hold",
        "priority":  "low",
        "core":  false,
        "recent7d":  2,
        "recent1d":  2,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "TECHNICALLY_TECHNICAL_DESIGN",
        "stage":  "in-work",
        "priority":  "medium",
        "core":  false,
        "recent7d":  6,
        "recent1d":  6,
        "totalHist":  112,
        "restingDays":  null
    },
    {
        "name":  "TOOLBOX",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  8,
        "recent1d":  6,
        "totalHist":  84,
        "restingDays":  null
    },
    {
        "name":  "VITRINE",
        "stage":  "development",
        "priority":  "medium",
        "core":  false,
        "recent7d":  23,
        "recent1d":  23,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "VIWOODS",
        "stage":  "development",
        "priority":  "high",
        "core":  true,
        "recent7d":  13,
        "recent1d":  11,
        "totalHist":  150,
        "restingDays":  null
    },
    {
        "name":  "WORKSPACE_OPS",
        "stage":  "in-work",
        "priority":  "high",
        "core":  true,
        "recent7d":  27,
        "recent1d":  27,
        "totalHist":  150,
        "restingDays":  null
    }
] };
